[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
token_timelock_vault = "AHuxcfexoU55eDhM8V5jk2U6ZJocjHVn8H5Y1RYm5qSC"

[toolchain]
anchor_version = "0.31.1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/usuario/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
